### PR TITLE
Fix #3 (https crashes)

### LINKED ISSUE #3: Enabling https crashes the bot
This is caused because the code loading the keys is wrong and weird

### PR DESCRIPTION
**Pull request by Blatoy**

### CODE REVIEW

File: bot/webserver.js [hunk 1]
```diff
@@ -50,7 +46,7 @@ module.exports.startAPIServer = () => {
     app.post("/api", webAPI.onPost);
 };
 
-if (credentials.key === undefined || credentials.certificate === undefined) {
+if (appConfig.privateKey === "" || appConfig.certificate === "") {
```
Comment (RedMser) [inline bot/webserver.js]: Might make more sense to use !appConfig.blalblaba? In case it's not defined in the json file for REASONS...

Comment (Blatoy) [reply bot/webserver.js]: Even better would be to use typeof. Even it should not be not defined if the user uses the install script, I'll change it

**Review by RedMser — APPROVED** [review]
